// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrF-P6-odqL8fKDvjSabPD48dhE7Ggn5Q',
    appId: '1:754114066705:web:03f85df7df30a6b92734b0',
    messagingSenderId: '754114066705',
    projectId: 'flutter-video-explorer',
    authDomain: 'flutter-video-explorer.firebaseapp.com',
    storageBucket: 'flutter-video-explorer.firebasestorage.app',
    measurementId: 'G-NMG98VH7R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzXv9Vd_vado2UMFM2hK567AApUbp7-u4',
    appId: '1:754114066705:android:57722612fe21363d2734b0',
    messagingSenderId: '754114066705',
    projectId: 'flutter-video-explorer',
    storageBucket: 'flutter-video-explorer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ8B0-2u7Qc7MfcDX5Dvv74P56fIt0z_E',
    appId: '1:754114066705:ios:84e1a9e406fb148f2734b0',
    messagingSenderId: '754114066705',
    projectId: 'flutter-video-explorer',
    storageBucket: 'flutter-video-explorer.firebasestorage.app',
    iosBundleId: 'com.example.flutterVideoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ8B0-2u7Qc7MfcDX5Dvv74P56fIt0z_E',
    appId: '1:754114066705:ios:84e1a9e406fb148f2734b0',
    messagingSenderId: '754114066705',
    projectId: 'flutter-video-explorer',
    storageBucket: 'flutter-video-explorer.firebasestorage.app',
    iosBundleId: 'com.example.flutterVideoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrF-P6-odqL8fKDvjSabPD48dhE7Ggn5Q',
    appId: '1:754114066705:web:4bc85e1826082e252734b0',
    messagingSenderId: '754114066705',
    projectId: 'flutter-video-explorer',
    authDomain: 'flutter-video-explorer.firebaseapp.com',
    storageBucket: 'flutter-video-explorer.firebasestorage.app',
    measurementId: 'G-SWPHDK725W',
  );
}
